Repository apollographql/eslint-plugin-graphql, pull requests merged in 2018-11, with the labels that each got.

#175 Add an example tagName for relay-modern in docs
  README.md
Labels: docs

#154 feat: add fraql env
  CHANGELOG.md
  README.md
  src/index.js
  test/makeRule.js
Labels: feature

#199 Required fields and fragments
  CHANGELOG.md
  src/customGraphQLValidationRules.js
  test/__fixtures__/required-fields-valid-id.graphql
  test/schema.graphql
  test/validationRules/required-fields.js
Labels: blocking, feature

#179 Fix schema caching for multi-schema workspaces
  CHANGELOG.md
  src/index.js
  test/graphqlconfig/index.js
  test/graphqlconfig/multiproject-literal/.graphqlconfig
Labels: blocking
