Repository apollographql/eslint-plugin-graphql, pull requests merged in 2018-04, with the labels that each got.

#121 Update list of available validators (as of GraphQL 0.13.2)
  README.md
  renovate.json
Labels: docs

#119 Adding support for graphql@0.12.0 and graphql@0.13.0
  .tav.yml
  .travis.yml
  README.md
  package-lock.json
  package.json
  test/graphqlconfig/index.js
  test/makeRule.js
  test/schema.graphql
  yarn.lock
Labels: feature

#137 Cache for parsing the schema
  CHANGELOG.md
  src/index.js
Labels: performance
